redis: &redis
  adapter: redis
  url: redis://localhost:6379/0

development: *redis

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: mile_high_bibliofiles_production
